version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: emergencycalls_db
    environment:
      POSTGRES_DB: emergencydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  edvantis-task-BE:
    build: ./edvantis-task-BE
    image: edvantis-task-backend
    container_name: emergencycalls_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/emergencydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - '8080:8080'

  edvantis-task-FE:
    build: ./edvantis-task-FE
    image: edvantis-task-frontend
    container_name: emergencycalls_frontend
    depends_on:
      - edvantis-task-BE
    ports:
      - '3000:80'
    # W kodzie frontu używasz "http://edvantis-task-BE:8080", co działa wewnątrz tej sieci Docker

volumes:
  db-data:
